package org.example.user.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.example.user.core.domain.UserWelcomeMailSent;
import org.example.user.core.domain.UserWelcomeMailSentExample;

public interface UserWelcomeMailSentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    long countByExample(UserWelcomeMailSentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    int deleteByExample(UserWelcomeMailSentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    int insert(UserWelcomeMailSent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    int insertSelective(UserWelcomeMailSent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    List<UserWelcomeMailSent> selectByExampleWithBLOBsWithRowbounds(UserWelcomeMailSentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    List<UserWelcomeMailSent> selectByExampleWithBLOBs(UserWelcomeMailSentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    List<UserWelcomeMailSent> selectByExampleWithRowbounds(UserWelcomeMailSentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    List<UserWelcomeMailSent> selectByExample(UserWelcomeMailSentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    UserWelcomeMailSent selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    int updateByExampleSelective(@Param("row") UserWelcomeMailSent row, @Param("example") UserWelcomeMailSentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") UserWelcomeMailSent row, @Param("example") UserWelcomeMailSentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    int updateByExample(@Param("row") UserWelcomeMailSent row, @Param("example") UserWelcomeMailSentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    int updateByPrimaryKeySelective(UserWelcomeMailSent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(UserWelcomeMailSent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_welcome_mail_sent
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    int updateByPrimaryKey(UserWelcomeMailSent row);
}