package org.example.user.core.domain;

import io.swagger.annotations.ApiModel;

import java.util.Date;

@ApiModel
public class UserModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_model.user_id
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_model.first_name
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_model.last_name
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_model.birthdate
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private String birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_model.gender
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_model.zipcode
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private Integer zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_model.deleted
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_model.gmt_create
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_model.gmt_modified
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_model.user_id
     *
     * @return the value of user_model.user_id
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_model.user_id
     *
     * @param userId the value for user_model.user_id
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_model.first_name
     *
     * @return the value of user_model.first_name
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_model.first_name
     *
     * @param firstName the value for user_model.first_name
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_model.last_name
     *
     * @return the value of user_model.last_name
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_model.last_name
     *
     * @param lastName the value for user_model.last_name
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_model.birthdate
     *
     * @return the value of user_model.birthdate
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_model.birthdate
     *
     * @param birthdate the value for user_model.birthdate
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate == null ? null : birthdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_model.gender
     *
     * @return the value of user_model.gender
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_model.gender
     *
     * @param gender the value for user_model.gender
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_model.zipcode
     *
     * @return the value of user_model.zipcode
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public Integer getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_model.zipcode
     *
     * @param zipcode the value for user_model.zipcode
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setZipcode(Integer zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_model.deleted
     *
     * @return the value of user_model.deleted
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_model.deleted
     *
     * @param deleted the value for user_model.deleted
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_model.gmt_create
     *
     * @return the value of user_model.gmt_create
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_model.gmt_create
     *
     * @param gmtCreate the value for user_model.gmt_create
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_model.gmt_modified
     *
     * @return the value of user_model.gmt_modified
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_model.gmt_modified
     *
     * @param gmtModified the value for user_model.gmt_modified
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}