package org.example.user.core.domain;

import java.util.Date;

public class UserPassword {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_passwords.user_id
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_passwords.hash_code
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    private String hashCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_passwords.deleted
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_passwords.gmt_create
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_passwords.gmt_modified
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_passwords.user_id
     *
     * @return the value of user_passwords.user_id
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_passwords.user_id
     *
     * @param userId the value for user_passwords.user_id
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_passwords.hash_code
     *
     * @return the value of user_passwords.hash_code
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public String getHashCode() {
        return hashCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_passwords.hash_code
     *
     * @param hashCode the value for user_passwords.hash_code
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public void setHashCode(String hashCode) {
        this.hashCode = hashCode == null ? null : hashCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_passwords.deleted
     *
     * @return the value of user_passwords.deleted
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_passwords.deleted
     *
     * @param deleted the value for user_passwords.deleted
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_passwords.gmt_create
     *
     * @return the value of user_passwords.gmt_create
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_passwords.gmt_create
     *
     * @param gmtCreate the value for user_passwords.gmt_create
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_passwords.gmt_modified
     *
     * @return the value of user_passwords.gmt_modified
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_passwords.gmt_modified
     *
     * @param gmtModified the value for user_passwords.gmt_modified
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}