package org.example.user.core.domain;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.deleted
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gmt_create
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gmt_modified
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.deleted
     *
     * @return the value of users.deleted
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.deleted
     *
     * @param deleted the value for users.deleted
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gmt_create
     *
     * @return the value of users.gmt_create
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gmt_create
     *
     * @param gmtCreate the value for users.gmt_create
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gmt_modified
     *
     * @return the value of users.gmt_modified
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gmt_modified
     *
     * @param gmtModified the value for users.gmt_modified
     *
     * @mbg.generated Sun Jul 02 16:40:50 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}