package org.example.user.core.domain;

import java.util.Date;

public class UserWelcomeMailSent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_welcome_mail_sent.user_id
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_welcome_mail_sent.mail_path
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private String mailPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_welcome_mail_sent.c_time
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private Date cTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_welcome_mail_sent.mail_content
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    private String mailContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_welcome_mail_sent.user_id
     *
     * @return the value of user_welcome_mail_sent.user_id
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_welcome_mail_sent.user_id
     *
     * @param userId the value for user_welcome_mail_sent.user_id
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_welcome_mail_sent.mail_path
     *
     * @return the value of user_welcome_mail_sent.mail_path
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public String getMailPath() {
        return mailPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_welcome_mail_sent.mail_path
     *
     * @param mailPath the value for user_welcome_mail_sent.mail_path
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setMailPath(String mailPath) {
        this.mailPath = mailPath == null ? null : mailPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_welcome_mail_sent.c_time
     *
     * @return the value of user_welcome_mail_sent.c_time
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_welcome_mail_sent.c_time
     *
     * @param cTime the value for user_welcome_mail_sent.c_time
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_welcome_mail_sent.mail_content
     *
     * @return the value of user_welcome_mail_sent.mail_content
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public String getMailContent() {
        return mailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_welcome_mail_sent.mail_content
     *
     * @param mailContent the value for user_welcome_mail_sent.mail_content
     *
     * @mbg.generated Wed Jul 05 18:00:47 CST 2023
     */
    public void setMailContent(String mailContent) {
        this.mailContent = mailContent == null ? null : mailContent.trim();
    }
}